### ISSUE TITLE
Cannot use this package with multiple projects on a single workstation

### ISSUE THREAD

**Issue by davidyaha** [bookmd/schema-migrations#3]
Based on the readme file:
https://github.com/bookmd/schema-migrations/blame/master/README.md#L22

The configuration file needs be on the METEOR_HOME dir which normally resolves to ~/.meteor.
Putting a config file in there will create a situation where you need to change the config file for each project you use. 

This might be a mistake and what was meant is that you use PROJECT_HOME which makes perfect sense..

Thanks ahead,
David

**Comment by davidyaha** [comment]
Just saw that it asks me to put settings file in the .meteor dir on the project.. Why is that? and also, the docs is not clear about it.

**Comment by chenrozenes** [comment]
You are right. When I wrote METEOR_HOME, I meant PROJECT_HOME. I'll fix the readme file.
In addition, You should place the settings file in the PROJECT_HOME directory. Also a mistake in the readme file. I'll fix that as well. Thanks
